# Generated by Django 4.2.4 on 2023-08-10 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(default="", max_length=25)),
                ("task_desc", models.TextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "todo",
            },
        ),
    ]
